name: Validate PR Title

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main]

jobs:
  pr-title:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@main
